/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountFavoritesRouteImport } from './routes/account.favorites'
import { Route as AccountInquiriesRouteImport } from './routes/account.inquiries'
import { Route as AccountListingsRouteImport } from './routes/account.listings'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountReservationsRouteImport } from './routes/account.reservations'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as VehiclesVehicleIdRouteImport } from './routes/vehicles.$vehicleId'
import { Route as AdminVehiclesIndexRouteImport } from './routes/admin.vehicles.index'
import { Route as AdminVehiclesVehicleIdRouteImport } from './routes/admin.vehicles.$vehicleId'
import { Route as AdminVehiclesNewRouteImport } from './routes/admin.vehicles.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountFavoritesRoute = AccountFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AccountRoute,
} as any)
const AccountInquiriesRoute = AccountInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AccountRoute,
} as any)
const AccountListingsRoute = AccountListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReservationsRoute = AccountReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AdminRoute,
} as any)
const VehiclesVehicleIdRoute = VehiclesVehicleIdRouteImport.update({
  id: '/vehicles/$vehicleId',
  path: '/vehicles/$vehicleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVehiclesIndexRoute = AdminVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiclesVehicleIdRoute = AdminVehiclesVehicleIdRouteImport.update({
  id: '/vehicles/$vehicleId',
  path: '/vehicles/$vehicleId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVehiclesNewRoute = AdminVehiclesNewRouteImport.update({
  id: '/vehicles/new',
  path: '/vehicles/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/inquiries': typeof AccountInquiriesRoute
  '/account/listings': typeof AccountListingsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reservations': typeof AccountReservationsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/vehicles/$vehicleId': typeof AdminVehiclesVehicleIdRoute
  '/admin/vehicles/new': typeof AdminVehiclesNewRoute
  '/admin/vehicles/': typeof AdminVehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/inquiries': typeof AccountInquiriesRoute
  '/account/listings': typeof AccountListingsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reservations': typeof AccountReservationsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/vehicles/$vehicleId': typeof AdminVehiclesVehicleIdRoute
  '/admin/vehicles/new': typeof AdminVehiclesNewRoute
  '/admin/vehicles': typeof AdminVehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sell': typeof SellRoute
  '/signup': typeof SignupRoute
  '/account/favorites': typeof AccountFavoritesRoute
  '/account/inquiries': typeof AccountInquiriesRoute
  '/account/listings': typeof AccountListingsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/reservations': typeof AccountReservationsRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/vehicles/$vehicleId': typeof AdminVehiclesVehicleIdRoute
  '/admin/vehicles/new': typeof AdminVehiclesNewRoute
  '/admin/vehicles/': typeof AdminVehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/browse'
    | '/contact'
    | '/financing'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sell'
    | '/signup'
    | '/account/favorites'
    | '/account/inquiries'
    | '/account/listings'
    | '/account/profile'
    | '/account/reservations'
    | '/admin/inquiries'
    | '/admin/payments'
    | '/admin/reservations'
    | '/vehicles/$vehicleId'
    | '/account/'
    | '/admin/'
    | '/admin/vehicles/$vehicleId'
    | '/admin/vehicles/new'
    | '/admin/vehicles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/contact'
    | '/financing'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sell'
    | '/signup'
    | '/account/favorites'
    | '/account/inquiries'
    | '/account/listings'
    | '/account/profile'
    | '/account/reservations'
    | '/admin/inquiries'
    | '/admin/payments'
    | '/admin/reservations'
    | '/vehicles/$vehicleId'
    | '/account'
    | '/admin'
    | '/admin/vehicles/$vehicleId'
    | '/admin/vehicles/new'
    | '/admin/vehicles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/browse'
    | '/contact'
    | '/financing'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sell'
    | '/signup'
    | '/account/favorites'
    | '/account/inquiries'
    | '/account/listings'
    | '/account/profile'
    | '/account/reservations'
    | '/admin/inquiries'
    | '/admin/payments'
    | '/admin/reservations'
    | '/vehicles/$vehicleId'
    | '/account/'
    | '/admin/'
    | '/admin/vehicles/$vehicleId'
    | '/admin/vehicles/new'
    | '/admin/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  ContactRoute: typeof ContactRoute
  FinancingRoute: typeof FinancingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellRoute: typeof SellRoute
  SignupRoute: typeof SignupRoute
  VehiclesVehicleIdRoute: typeof VehiclesVehicleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/favorites': {
      id: '/account/favorites'
      path: '/favorites'
      fullPath: '/account/favorites'
      preLoaderRoute: typeof AccountFavoritesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/inquiries': {
      id: '/account/inquiries'
      path: '/inquiries'
      fullPath: '/account/inquiries'
      preLoaderRoute: typeof AccountInquiriesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/listings': {
      id: '/account/listings'
      path: '/listings'
      fullPath: '/account/listings'
      preLoaderRoute: typeof AccountListingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/reservations': {
      id: '/account/reservations'
      path: '/reservations'
      fullPath: '/account/reservations'
      preLoaderRoute: typeof AccountReservationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/vehicles/$vehicleId': {
      id: '/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof VehiclesVehicleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vehicles/': {
      id: '/admin/vehicles/'
      path: '/vehicles'
      fullPath: '/admin/vehicles/'
      preLoaderRoute: typeof AdminVehiclesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicles/$vehicleId': {
      id: '/admin/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/admin/vehicles/$vehicleId'
      preLoaderRoute: typeof AdminVehiclesVehicleIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vehicles/new': {
      id: '/admin/vehicles/new'
      path: '/vehicles/new'
      fullPath: '/admin/vehicles/new'
      preLoaderRoute: typeof AdminVehiclesNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AccountRouteChildren {
  AccountFavoritesRoute: typeof AccountFavoritesRoute
  AccountInquiriesRoute: typeof AccountInquiriesRoute
  AccountListingsRoute: typeof AccountListingsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountReservationsRoute: typeof AccountReservationsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountFavoritesRoute: AccountFavoritesRoute,
  AccountInquiriesRoute: AccountInquiriesRoute,
  AccountListingsRoute: AccountListingsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountReservationsRoute: AccountReservationsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminVehiclesVehicleIdRoute: typeof AdminVehiclesVehicleIdRoute
  AdminVehiclesNewRoute: typeof AdminVehiclesNewRoute
  AdminVehiclesIndexRoute: typeof AdminVehiclesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminVehiclesVehicleIdRoute: AdminVehiclesVehicleIdRoute,
  AdminVehiclesNewRoute: AdminVehiclesNewRoute,
  AdminVehiclesIndexRoute: AdminVehiclesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BrowseRoute: BrowseRoute,
  ContactRoute: ContactRoute,
  FinancingRoute: FinancingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellRoute: SellRoute,
  SignupRoute: SignupRoute,
  VehiclesVehicleIdRoute: VehiclesVehicleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
